# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e2defc953d3d7903a80a2c1b6ae54d97ae6760b60db0eb74a5ff2e46747145bdb9de31b23d8ee07089ef2d234897d3df92002ddfb7fd060b1bf64c12327dd6d

test:
  secret_key_base: e99009138573afc0b0c8bdc9e72c5bd14e642d65dc774dd6b410e702bcbfa5170534ab913ff0de14fbeb46143f32c62d1dbb25e82597373d0007a8b82591e868

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
